kind: Secret
apiVersion: v1
metadata:
  name: azdevops
stringData:
  AZP_TOKEN: {{ .Values.azpdevops.token }}
  AZP_URL: {{ .Values.azpdevops.url }}
  AZP_POOL: {{ .Values.azpdevops.pool }}
  AZP_AGENT_NAME="OpenShift Agent - ubi9"
type: Opaque
