kind: Secret
apiVersion: v1
metadata:
  name: azdevops
stringData:
  AZP_TOKEN: {{ .Values.azpdevops.token }}
  AZP_URL: {{ .Values.azpdevops.url }}
  AZP_POOL: {{ .Values.azpdevops.pool }}
  AZP_AGENT_NAME: "OpenShift Agent - ubi9"
  VSTS_HTTP_PROXY: {{ .Values.azpdevops.proxy }}
  VSTS_HTTP_NO_PROXY: {{ .Values.azpdevops.no_proxy }}
  VSTS_HTTP_PROXY_USERNAME: {{ .Values.azpdevops.proxy_username }}
  VSTS_HTTP_PROXY_PASSWORD: {{ .Values.azpdevops.proxy_password }}
type: Opaque
