ARG base_image_repository
ARG base_image_digest

FROM ${base_image_repository}@${base_image_digest} as builder

WORKDIR /tmp

RUN dnf install binutils gcc make openssl-devel openssl perl -y
RUN curl -LsS https://github.com/curl/curl/releases/download/curl-8_13_0/curl-8.13.0.tar.gz| tar -xz
RUN cd curl-8.13.0 && ./configure --prefix=/opt/curl/ --with-openssl --without-libpsl && make && make install
RUN curl -LsS https://github.com/open-policy-agent/gatekeeper/releases/download/v3.18.2/gator-v3.18.2-linux-amd64.tar.gz | tar -xz & wait $! && \
    chmod a+rx gator
RUN /opt/curl/bin/curl --version

ARG base_image_repository
ARG base_image_digest

FROM ${base_image_repository}@${base_image_digest}

ENV TARGETARCH="linux-x64"
# ENV AZP_URL=${AZP_URL}
# ENV AZP_TOKEN=${AZP_TOKEN}

ARG base_image_digest
ARG base_image_repository
ARG base_image_tag

# $(git config --get remote.origin.url)
ARG git_origin_url
# $(git rev-parse HEAD)
ARG git_revision
# $(git rev-parse --abbrev-ref HEAD)
# note: this is a a semver git tag typically
ARG src_version
# ${date -u +'%Y-%m-%dT%H:%M:%SZ'}
ARG created
# group emails of the team that supports this image
ARG author_emails
# the build host url
ARG build_host
# a unique id for the build of this image
ARG build_id

LABEL org.opencontainers.image.title=azp-agent \
    org.opencontainers.image.description="An example ubi9 azp-agent." \
    org.opencontainers.image.source=${git_origin_url} \
    org.opencontainers.image.revision=${git_revision} \
    org.opencontainers.image.base.digest=${base_image_digest} \
    org.opencontainers.image.base.name=${base_image_repository}:${base_image_tag} \
    org.opencontainers.image.version=${src_version} \
    org.opencontainers.image.created=${created} \
    org.opencontainers.image.authors=${author_emails} \    
    com.example.org.context.build-host=${build_host} \
    com.example.org.context.build-id=${build_id}

# https://access.redhat.com/discussions/a43b51f2-737a-4684-a7df-a1dec1dd66b6

COPY --from=builder /opt/curl /opt/curl
COPY --from=builder /tmp/gator /usr/local/bin/gator

RUN ln -s /opt/curl/bin/curl /usr/local/bin/curl

WORKDIR /azp

COPY ./download.sh .

COPY ./start.sh .

RUN --mount=type=secret,id=azp_url \
    --mount=type=secret,id=azp_token \
    rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    dnf update -y && \
    dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm && \
    dnf install -y git jq libicu procps && \
    dnf install -y azure-cli && \
    dnf clean all && \
    rm -rf /var/cache/dnf && \
    chmod +x download.sh && \
    ./download.sh && \
    rm download.sh && \
    chown -R 1001:0 /azp && \
    chmod -R g=u /azp && \
    chmod +x *.sh

USER 1001

ENTRYPOINT [ "./start.sh" ]
